#!/usr/bin/python
def greet(kumari):

    print kumari;
greet(kumari=123)
 #return()
#print ( "hello", sai

"""def print( name, age ):
    print "name:", name
    print "age:", age
 print( age=23, name="miki"""
 
 thank u
